//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abono()
        {
            this.CuentaPorCobrar = new HashSet<CuentaPorCobrar>();
        }
    
        public string codigo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public decimal monto { get; set; }
        public string idMetodoPago { get; set; }
        public string cedula { get; set; }
        public string idFactura { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaPorCobrar> CuentaPorCobrar { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
    }
}
