//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.UI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abono> Abono { get; set; }
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Correo> Correo { get; set; }
        public virtual DbSet<CuentaPorCobrar> CuentaPorCobrar { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<MetodoPago> MetodoPago { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Telefono> Telefono { get; set; }
    
        public virtual ObjectResult<Nullable<int>> create_abono(string codigo, Nullable<System.DateTime> fecha, Nullable<decimal> monto, string idMetodoPago, string cedula, string idFactura)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(decimal));
    
            var idMetodoPagoParameter = idMetodoPago != null ?
                new ObjectParameter("idMetodoPago", idMetodoPago) :
                new ObjectParameter("idMetodoPago", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var idFacturaParameter = idFactura != null ?
                new ObjectParameter("idFactura", idFactura) :
                new ObjectParameter("idFactura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_abono", codigoParameter, fechaParameter, montoParameter, idMetodoPagoParameter, cedulaParameter, idFacturaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_canton(string idCanton, string nombre)
        {
            var idCantonParameter = idCanton != null ?
                new ObjectParameter("idCanton", idCanton) :
                new ObjectParameter("idCanton", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_canton", idCantonParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_cliente(string cedula, string nombre, Nullable<decimal> saldoGeneral, string direccionExacta, string idDistrito)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var saldoGeneralParameter = saldoGeneral.HasValue ?
                new ObjectParameter("saldoGeneral", saldoGeneral) :
                new ObjectParameter("saldoGeneral", typeof(decimal));
    
            var direccionExactaParameter = direccionExacta != null ?
                new ObjectParameter("direccionExacta", direccionExacta) :
                new ObjectParameter("direccionExacta", typeof(string));
    
            var idDistritoParameter = idDistrito != null ?
                new ObjectParameter("idDistrito", idDistrito) :
                new ObjectParameter("idDistrito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_cliente", cedulaParameter, nombreParameter, saldoGeneralParameter, direccionExactaParameter, idDistritoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_correo(string cedulaCliente, string correo)
        {
            var cedulaClienteParameter = cedulaCliente != null ?
                new ObjectParameter("cedulaCliente", cedulaCliente) :
                new ObjectParameter("cedulaCliente", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_correo", cedulaClienteParameter, correoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_cuentaPorCobrar(string codigo, Nullable<int> plazo, Nullable<System.DateTime> vencimiento, Nullable<decimal> saldo, string idFactura, string cedula, string codigoAbono)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var plazoParameter = plazo.HasValue ?
                new ObjectParameter("plazo", plazo) :
                new ObjectParameter("plazo", typeof(int));
    
            var vencimientoParameter = vencimiento.HasValue ?
                new ObjectParameter("vencimiento", vencimiento) :
                new ObjectParameter("vencimiento", typeof(System.DateTime));
    
            var saldoParameter = saldo.HasValue ?
                new ObjectParameter("saldo", saldo) :
                new ObjectParameter("saldo", typeof(decimal));
    
            var idFacturaParameter = idFactura != null ?
                new ObjectParameter("idFactura", idFactura) :
                new ObjectParameter("idFactura", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var codigoAbonoParameter = codigoAbono != null ?
                new ObjectParameter("codigoAbono", codigoAbono) :
                new ObjectParameter("codigoAbono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_cuentaPorCobrar", codigoParameter, plazoParameter, vencimientoParameter, saldoParameter, idFacturaParameter, cedulaParameter, codigoAbonoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_distrito(string idDistrito, string nombre)
        {
            var idDistritoParameter = idDistrito != null ?
                new ObjectParameter("idDistrito", idDistrito) :
                new ObjectParameter("idDistrito", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_distrito", idDistritoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_factura(string idFactura, Nullable<System.DateTime> fecha, Nullable<decimal> montoBruto, Nullable<decimal> montoDescuento, Nullable<decimal> montoImpuesto, Nullable<decimal> montoNeto, string notas, Nullable<bool> credito, Nullable<bool> contado, string cedula, string idSucursal)
        {
            var idFacturaParameter = idFactura != null ?
                new ObjectParameter("idFactura", idFactura) :
                new ObjectParameter("idFactura", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var montoBrutoParameter = montoBruto.HasValue ?
                new ObjectParameter("montoBruto", montoBruto) :
                new ObjectParameter("montoBruto", typeof(decimal));
    
            var montoDescuentoParameter = montoDescuento.HasValue ?
                new ObjectParameter("montoDescuento", montoDescuento) :
                new ObjectParameter("montoDescuento", typeof(decimal));
    
            var montoImpuestoParameter = montoImpuesto.HasValue ?
                new ObjectParameter("montoImpuesto", montoImpuesto) :
                new ObjectParameter("montoImpuesto", typeof(decimal));
    
            var montoNetoParameter = montoNeto.HasValue ?
                new ObjectParameter("montoNeto", montoNeto) :
                new ObjectParameter("montoNeto", typeof(decimal));
    
            var notasParameter = notas != null ?
                new ObjectParameter("notas", notas) :
                new ObjectParameter("notas", typeof(string));
    
            var creditoParameter = credito.HasValue ?
                new ObjectParameter("credito", credito) :
                new ObjectParameter("credito", typeof(bool));
    
            var contadoParameter = contado.HasValue ?
                new ObjectParameter("contado", contado) :
                new ObjectParameter("contado", typeof(bool));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var idSucursalParameter = idSucursal != null ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_factura", idFacturaParameter, fechaParameter, montoBrutoParameter, montoDescuentoParameter, montoImpuestoParameter, montoNetoParameter, notasParameter, creditoParameter, contadoParameter, cedulaParameter, idSucursalParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_metodoPago(string idMetodoPago, string nombre, string metodo)
        {
            var idMetodoPagoParameter = idMetodoPago != null ?
                new ObjectParameter("idMetodoPago", idMetodoPago) :
                new ObjectParameter("idMetodoPago", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var metodoParameter = metodo != null ?
                new ObjectParameter("metodo", metodo) :
                new ObjectParameter("metodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_metodoPago", idMetodoPagoParameter, nombreParameter, metodoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_provincia(string idProvincia, string nombre)
        {
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("idProvincia", idProvincia) :
                new ObjectParameter("idProvincia", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_provincia", idProvinciaParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_Sucursal(string idSucursal, string nombre)
        {
            var idSucursalParameter = idSucursal != null ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_Sucursal", idSucursalParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> create_telefono(string cedulaCliente, string numTelefono)
        {
            var cedulaClienteParameter = cedulaCliente != null ?
                new ObjectParameter("cedulaCliente", cedulaCliente) :
                new ObjectParameter("cedulaCliente", typeof(string));
    
            var numTelefonoParameter = numTelefono != null ?
                new ObjectParameter("numTelefono", numTelefono) :
                new ObjectParameter("numTelefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("create_telefono", cedulaClienteParameter, numTelefonoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_canton(string idCanton)
        {
            var idCantonParameter = idCanton != null ?
                new ObjectParameter("idCanton", idCanton) :
                new ObjectParameter("idCanton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_canton", idCantonParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_cliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_cliente", cedulaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_distrito(string idDistrito)
        {
            var idDistritoParameter = idDistrito != null ?
                new ObjectParameter("idDistrito", idDistrito) :
                new ObjectParameter("idDistrito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_distrito", idDistritoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_provincia(string idProvincia)
        {
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("idProvincia", idProvincia) :
                new ObjectParameter("idProvincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_provincia", idProvinciaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_Sucursal(string idSucursal)
        {
            var idSucursalParameter = idSucursal != null ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_Sucursal", idSucursalParameter);
        }
    
        public virtual ObjectResult<get_abonos_Result> get_abonos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_abonos_Result>("get_abonos");
        }
    
        public virtual ObjectResult<get_cantones_Result> get_cantones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_cantones_Result>("get_cantones");
        }
    
        public virtual ObjectResult<get_clientes_Result> get_clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_clientes_Result>("get_clientes");
        }
    
        public virtual ObjectResult<string> get_correos_cliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("get_correos_cliente", cedulaParameter);
        }
    
        public virtual ObjectResult<get_cuentaPorCobrar_Result> get_cuentaPorCobrar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_cuentaPorCobrar_Result>("get_cuentaPorCobrar");
        }
    
        public virtual ObjectResult<get_distritos_Result> get_distritos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_distritos_Result>("get_distritos");
        }
    
        public virtual ObjectResult<get_facturas_Result> get_facturas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_facturas_Result>("get_facturas");
        }
    
        public virtual ObjectResult<get_metodoPago_Result> get_metodoPago()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_metodoPago_Result>("get_metodoPago");
        }
    
        public virtual ObjectResult<get_notas_Result> get_notas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_notas_Result>("get_notas");
        }
    
        public virtual ObjectResult<get_provincias_Result> get_provincias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_provincias_Result>("get_provincias");
        }
    
        public virtual ObjectResult<get_sucursal_Result> get_sucursal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_sucursal_Result>("get_sucursal");
        }
    
        public virtual ObjectResult<string> get_telefonos_cliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("get_telefonos_cliente", cedulaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> modify_abono(string codigo, Nullable<System.DateTime> fecha, Nullable<decimal> monto, string idMetodoPago, string cedula, string idFactura)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(decimal));
    
            var idMetodoPagoParameter = idMetodoPago != null ?
                new ObjectParameter("idMetodoPago", idMetodoPago) :
                new ObjectParameter("idMetodoPago", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var idFacturaParameter = idFactura != null ?
                new ObjectParameter("idFactura", idFactura) :
                new ObjectParameter("idFactura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("modify_abono", codigoParameter, fechaParameter, montoParameter, idMetodoPagoParameter, cedulaParameter, idFacturaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> modify_canton(string idCanton, string nombre)
        {
            var idCantonParameter = idCanton != null ?
                new ObjectParameter("idCanton", idCanton) :
                new ObjectParameter("idCanton", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("modify_canton", idCantonParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> modify_cliente(string cedula, string nombre, Nullable<decimal> saldoGeneral, string direccionExacta, string idDistrito)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var saldoGeneralParameter = saldoGeneral.HasValue ?
                new ObjectParameter("saldoGeneral", saldoGeneral) :
                new ObjectParameter("saldoGeneral", typeof(decimal));
    
            var direccionExactaParameter = direccionExacta != null ?
                new ObjectParameter("direccionExacta", direccionExacta) :
                new ObjectParameter("direccionExacta", typeof(string));
    
            var idDistritoParameter = idDistrito != null ?
                new ObjectParameter("idDistrito", idDistrito) :
                new ObjectParameter("idDistrito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("modify_cliente", cedulaParameter, nombreParameter, saldoGeneralParameter, direccionExactaParameter, idDistritoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> modify_correo(string cedulaCliente, string correo)
        {
            var cedulaClienteParameter = cedulaCliente != null ?
                new ObjectParameter("cedulaCliente", cedulaCliente) :
                new ObjectParameter("cedulaCliente", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("modify_correo", cedulaClienteParameter, correoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> modify_distrito(string idDistrito, string nombre)
        {
            var idDistritoParameter = idDistrito != null ?
                new ObjectParameter("idDistrito", idDistrito) :
                new ObjectParameter("idDistrito", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("modify_distrito", idDistritoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<string> modify_provincia(string idProvincia, string nombre)
        {
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("idProvincia", idProvincia) :
                new ObjectParameter("idProvincia", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("modify_provincia", idProvinciaParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> modify_Sucursal(string idSucursal, string nombre)
        {
            var idSucursalParameter = idSucursal != null ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("modify_Sucursal", idSucursalParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> modify_telefono(string cedulaCliente, string numTelefono)
        {
            var cedulaClienteParameter = cedulaCliente != null ?
                new ObjectParameter("cedulaCliente", cedulaCliente) :
                new ObjectParameter("cedulaCliente", typeof(string));
    
            var numTelefonoParameter = numTelefono != null ?
                new ObjectParameter("numTelefono", numTelefono) :
                new ObjectParameter("numTelefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("modify_telefono", cedulaClienteParameter, numTelefonoParameter);
        }
    }
}
