//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemAdmin.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public string idNota { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public decimal monto { get; set; }
        public string notas { get; set; }
        public bool notaCredito { get; set; }
        public bool notaDebido { get; set; }
        public string cedula { get; set; }
        public string idFactura { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
